#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import clutter, theme, marx

stage = clutter.Stage()
stage.set_color(theme.system.bg)
stage.set_user_resizable(True)
stage.set_title('Te✯tMarx')

stage.connect('destroy', clutter.main_quit)

marx = marx.Marx()
stage.add(marx)
stage.set_key_focus(marx)

def on_stage_resize(source, allocation, flags):
    marx.set_size(*allocation.size)

stage.connect('allocation-changed', on_stage_resize)

stage.show()

clutter.main()
